<center>
<img src="https://cdn.megabonus.com/images/shop_logo/skillbox.png"/>
    
# Курс аналитик данных на Python
## Модуль 2.1. Numpy basics. Ищем пересечение в 2-х массивах.

Это библиотека для всевозможных математических операций, с большим количеством реализованных методов и возможностью реализовывать свою логику эффективно.  <br>
Например векторные и матричные произведения, которые используюся в машинном обучении, а также рассчет различных статистик.

Импортируем библиотеку [**numpy**](https://docs.scipy.org/doc/numpy-1.15.1/reference/) и сократим ее название для удобства и поддержания общепринятых обозначений. <br>

In [ ]:
import numpy as np

Основа [**numpy**](https://docs.scipy.org/doc/numpy-1.15.1/reference/) это вектора (**array**) и матрицы (**matrix**).<br>
Создадим вектор и попробуем возможности библиотеки.

— np.array — создает массив, элементы которого задаются массивоподобным объектом, который, например, может быть (вложенным) списком Python, кортежем, итерируемой последовательностью или другим экземпляром ndarray. <br>
— np.zeros — создает массив с указанными размерами и типом данных, заполненный нулями.<br>
— np.ones — создает массив с указанными размерами и типом данных, который заполняется единицами.<br>
— np.diag — создает диагональный массив с указанными значениями по диагонали и нулями в других местах.<br>
— np.arange — создает массив с равномерно распределенными значениями между указанными значениями начала, конца и приращения.<br>
— np.linspace — создает массив со значениями, равномерно распределенными между указанными начальным и конечным значениями, используя указанное количество элементов.<br>
— np.logspace — создает массив со значениями, логарифмически разнесенными между заданными начальным и конечным значениями.<br>
— np.meshgrid — генерирует матрицы координат (и многомерные массивы координат) из одномерных векторов координат.<br>
— np.fromfunction — создает массив и заполняет его значениями, указанными заданной функцией, которая оценивается для каждой комбинации индексов для заданного размера массива.<br>
— np.fromfile — создает массив с данными из двоичного (или текстового) файла. NumPy также предоставляет соответствующую функцию np.tofile, с помощью которой массивы NumPy можно сохранять на диск, а затем считывать обратно с помощью np.fromfile.<br>
— np.genfromtxt, np.loadtxt — создание массива из данных, считанных из текстового файла, например, файла значений, разделенных запятыми (CSV). Функция np.genfromtxt также поддерживает файлы данных с отсутствующими значениями.
— np.random.rand — генерирует массив со случайными числами, равномерно распределенными между 0 и 1. В модуле np.random также доступны другие типы распределений.<br>

### Вектора

In [ ]:
a = np.array([1, 2, 3, 4, 5])

In [ ]:
type(a)

numpy.ndarray

In [ ]:
a.shape

(5,)

In [ ]:
print(a[0], a[1], a[3]) # индексация по элементам

1 2 4


In [ ]:
a[:2] # индексация диапазоном

array([1, 2])

In [ ]:
a[-2:] # берем последний элемент в массиве

array([4, 5])

In [ ]:
a[::-1] # перевернуть массив

array([5, 4, 3, 2, 1])

In [ ]:
a[0] = 5 # операция присвоения
a

array([5, 2, 3, 4, 5])

In [ ]:
a = np.array(range(0,10))
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
b = np.array([1 for i in range(0,10)])
b

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [ ]:
a + b

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
print(a + 5)

b = np.array([1, 2.0, 3, 4, 'lol'])
b * 5

[10  7  8  9 10]


UFuncTypeError: ignored

In [ ]:
# уникальные элементы np-списка
print(np.unique(a))
print(np.unique(b))

[0 1 2 3 4 5 6 7 8 9]
[1]


In [ ]:
# создаём вектор случайных значений длины 5
import random
random.choices(range(0,100), k = 5) #k =random.randint(3,10))

[11, 46, 21, 17, 84]

In [ ]:
# рандомно сгенерим список списков
[random.choices(range(0,1000), k = 3) for i in range (0,3)]

[[349, 535, 3], [430, 935, 194], [921, 227, 264]]

### Матрицы

Матрицы по сути это таблички без границ.

In [ ]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
a[:,::]

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
print(type(a))

<class 'numpy.ndarray'>


In [ ]:
# обращаем все строки матрицы
# : синтаксис в скобках означает "каждую строку обратить "
a[:,::-1]

array([[ 4,  3,  2,  1],
       [ 8,  7,  6,  5],
       [12, 11, 10,  9]])

In [ ]:
print('Наша матрица:')
print(a)
print('---')
print('Наша распрямленная матрица:')
print(a.flatten())

Наша матрица:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
---
Наша распрямленная матрица:
[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [ ]:
a.nbytes

96

In [ ]:
a.shape

(3, 4)

In [ ]:
a.shape[0]* a.shape[1]*8

96

### Как выбрать отдельные элементы из numpy матрицы

In [ ]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

### Индексируемся по строкам матрицы.

In [ ]:
# Первый ряд, помните о том что индексация в Python начинается с 0.
row_r1 = a[1, :] # Запиcь в скобках по-символьно означает, что выбрать из матрицы 1-ю строку и её все элементы
row_r1

array([5, 6, 7, 8])

In [ ]:
row_r2 = a[:2, :3] # Запиcь в скобках по-символьно означает, что выбрать из матрицы строки от 0-й до 1 -й и у каждой строки выбрать элементы от 0-го до 2-го
row_r2

array([[1, 2, 3],
       [5, 6, 7]])

In [ ]:
row_r2.base

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
print(row_r1, row_r1.shape)
print(row_r2, row_r2.shape)

[5 6 7 8] (4,)
[[1 2 3]
 [5 6 7]] (2, 3)


In [ ]:
row_r2

array([[1, 2, 3],
       [5, 6, 7]])

In [ ]:
row_r2.base # Посмотреть изначальную матрицу

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

### Индексируемся по колонкам матрицы.

In [ ]:
a = np.array([random.choices(range(0,10), k = 3) for i in range (0,3)])
a

array([[9, 6, 2],
       [6, 4, 7],
       [6, 2, 6]])

In [ ]:
# Выведем на экран все сколонки матрицы
for i in range(0,a.shape[1]):
  print(a[:, i])

[9 6 6]
[6 4 2]
[2 7 6]


In [ ]:
# обратим все колонки матрицы
a[::-1,:]

array([[6, 2, 6],
       [6, 4, 7],
       [9, 6, 2]])

In [ ]:
a[::-1,::-1]

array([[6, 2, 6],
       [7, 4, 6],
       [2, 6, 9]])

In [ ]:
col_r1 = a[:, 1]
print(col_r1)
print('---')
print(col_r1.shape)

[6 4 2]
---
(3,)


In [ ]:
col_r2 = a[:, 1:3]
print(col_r2)
print('---')
print(col_r2.shape)

[[6 2]
 [4 7]
 [2 6]]
---
(3, 2)


In [ ]:
c = a.flatten()
c

array([9, 6, 2, 6, 4, 7, 6, 2, 6])

In [ ]:
mtrx = c.reshape(3,3)
mtrx

array([[9, 6, 2],
       [6, 4, 7],
       [6, 2, 6]])

In [ ]:
mtrx.T

array([[9, 6, 6],
       [6, 4, 2],
       [2, 7, 6]])

### Операции

In [ ]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)
print(x)
print('--'*8)
print(y)

[[1. 2.]
 [3. 4.]]
----------------
[[5. 6.]
 [7. 8.]]


In [ ]:
# Поэлементное сложение
print(x + y)
print('--'*8)
print(np.add(x, y))

[[ 6.  8.]
 [10. 12.]]
----------------
[[ 6.  8.]
 [10. 12.]]


In [ ]:
# Поэлементное вычитание
# [[-4.0 -4.0]
#  [-4.0 -4.0]]
print(x - y)
print('--'*8)
print(np.subtract(x, y))

[[-4. -4.]
 [-4. -4.]]
----------------
[[-4. -4.]
 [-4. -4.]]


In [ ]:
import time

print('Поэлементное умножение')
# [[ 5.0 12.0]
#  [21.0 32.0]]
print(x * y)
print(np.multiply(x, y))
print('--'*18)
print('Поэлементное деление')
# [[ 0.2         0.33333333]
#  [ 0.42857143  0.5       ]]
print(x / y)
print(np.divide(x, y))
print('--'*18)
print('Поэлементное взятие квадратного корня')
# [[ 1.          1.41421356]
#  [ 1.73205081  2.        ]]
print(np.sqrt(x))
print('--'*18)
%time

Поэлементное умножение
[[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]]
------------------------------------
Поэлементное деление
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
------------------------------------
Поэлементное взятие квадратного корня
[[1.         1.41421356]
 [1.73205081 2.        ]]
------------------------------------
CPU times: user 4 µs, sys: 0 ns, total: 4 µs
Wall time: 6.91 µs


### Некоторые полезные методы

### Argmax/argmin
argmax - индекс максимального элемента <br>
argmin - индекс минимального элемента

In [ ]:
x = np.array(random.choices(range(0,100), k = random.randint(3,20)))
print(x)
print(type(x))

[55  6  5 48 31 62  6 83 56 91 85 32 19 84 49]
<class 'numpy.ndarray'>


In [ ]:
print(f'максимальный элемент = {x.max()}, его индекс = {x.argmax()}')
print(f'минимальный элемент = {x.min()}, его индекс = {x.argmin()}')

максимальный элемент = 91, его индекс = 9
минимальный элемент = 5, его индекс = 2


In [ ]:
x[5] = 99
x[9] = -99
x

array([ 55,   6,   5,  48,  31,  99,   6,  83,  56, -99,  85,  32,  19,
        84,  49])

In [ ]:
print(f'максимальный элемент = {x.max()}, его индекс = {x.argmax()}')
print(f'минимальный элемент = {x.min()}, его индекс = {x.argmin()}')

максимальный элемент = 99, его индекс = 5
минимальный элемент = -99, его индекс = 9


### Транспонирование матрицы

In [ ]:
matr = np.array([random.choices(range(0,100), k = 3) for i in range(0,3)])
print(matr)
print(type(matr))

[[ 2  0 46]
 [44 78 69]
 [78 14 13]]
<class 'numpy.ndarray'>


In [ ]:
matr.T # транспонирование или переворачивание объекта вокруг диагональной оси

array([[ 2, 44, 78],
       [ 0, 78, 14],
       [46, 69, 13]])

In [ ]:
a = np.array([['may','june','july','august'], [100,101,102,500]])
print(a)
print('--'*28)
print(a.T)

[['may' 'june' 'july' 'august']
 ['100' '101' '102' '500']]
--------------------------------------------------------
[['may' '100']
 ['june' '101']
 ['july' '102']
 ['august' '500']]


In [ ]:
print(x)
print(x.T)

[  0   1   2   3   4  99   6   7   8 -99  10]
[  0   1   2   3   4  99   6   7   8 -99  10]


### Объединение с помощью функции Append

In [ ]:
a = np.array(['may', 'june', 'july', 'august'])
a.append('august')

AttributeError: ignored

In [ ]:
?np.append()

Object `np.append()` not found.


In [ ]:
print(np.append(a,'august'))
print(a) # исходный объект не обновился
a = np.append(a,'august') # Надо переназначать объект/ присваивать его заново после операций, чтобы он обновился в результате применения операции.
print(a)

['may' 'june' 'july' 'august' 'august']
['may' 'june' 'july' 'august']
['may' 'june' 'july' 'august' 'august']


### Unique

In [ ]:
np.unique(a)

array(['august', 'july', 'june', 'may'], dtype='<U6')

In [ ]:
b = np.unique(a)
b

array(['august', 'july', 'june', 'may'], dtype='<U6')

In [ ]:
a

array(['may', 'june', 'july', 'august', 'august'], dtype='<U6')

### Concatenate

In [ ]:
spring = np.array(['march', 'april', 'may'])
summer = np.array(['june', 'july', 'august'])
warm_months = np.concatenate([spring, summer])
warm_months

array(['march', 'april', 'may', 'june', 'july', 'august'], dtype='<U6')

In [ ]:
??np.concatenate

### Nonzero

In [ ]:
a = np.array([100,101,102,500,0])
print('Наш вектор длиной:')
print(len(a))
print('---')
print('Метод покажет ненулевые индексы:')
print(np.nonzero(a))
print('Вывести значения можно так:')
print(a[np.nonzero(a)])
print('Проверим длину:')
print(len(a[np.nonzero(a)]))

#print(len(np.argwhere(a)))

Наш вектор длиной:
5
---
Метод покажет ненулевые индексы:
(array([0, 1, 2, 3]),)
Вывести значения можно так:
[100 101 102 500]
Проверим длину:
4


## Пересечение двух массивов

Нередко стоит задача найти общие объекты среди 2-х массивов и найти общие элементы.

In [ ]:
a = np.array([1,10,100,1000])
b = np.array([1,4,100])

А теперь пересечем их методом **np.intersect1d()** и передадим 2 вектора в качестве аргументов.

In [ ]:
c = np.intersect1d(a, b)
c

array([  1, 100])

Чтобы в интеренете не искать документацию, опять же, можно использовать встроенную документацию в Python.

In [ ]:
??np.intersect1d

Этот метод, конечно, работает не только с цифрами, но и с другими объектами, например с строками.

In [ ]:
a = np.array(['Юля', 'Олег', 'Роман', 'Иван'])
b = np.array(['Юля','Иван','Леонид'])

In [ ]:
c = np.intersect1d(a,b)
c

array(['Иван', 'Юля'], dtype='<U6')

Вспомним метод, который показывает размерности объекта. <br>
И не смотря на то, что у нас всего-лишь вектор, метод **.size** выведет нам количество объектов, которые содержатся в результирующем векторе ( который тоже в свою очередь является объектом, потому что все в Python, как мы помним, это объект!).

In [ ]:
c.size

2

Тоже самое мы можем найти, используя метод **len( )**, встроенный в язык Python, который измеряет длину вектора.

In [ ]:
len(c)

2

Так же часто встает задача найти значения, которые не являются общими, эдакие эксклюзивные значения из 2х векторов/наборов объектов.
Это тоже можно сделать в одну строчку с помощью метода **.setxor1d()** передав ему 2 вектора в качестве аргументов.

In [ ]:
??np.
(a, b)

### Более жизненный пример.

На "игрушечном" ималеньком массиве мы смогли построить пересечение. Принцип остается тот же, если мы ,например, хотим найти пересечение между большим количеством объектов.<br>
Допустим у нас есть какие-либо id пользователей и нам нужно найти пересечение между группами.

Импортируем ниже библиотеку random, с помощью которой можно нагенерить числа, например 4-х значные.<br>
Сделаем списки

In [ ]:
import random
import time

%time
customer_ids_a = random.sample(range(1000000, 5000000), 1000000)
customer_ids_b = random.sample(range(1000000, 5000000), 1000000)

CPU times: user 2 µs, sys: 0 ns, total: 2 µs
Wall time: 6.2 µs


Посмотрим на наши массивы, делая срезы в 5 и 10 элементов.

In [ ]:
print('Массив А:%s'%customer_ids_a[:5])
print('Массив Б:%s'%customer_ids_b[:10])

Массив А:[4047716, 2466069, 2773648, 1427093, 4206497]
Массив Б:[1572553, 4044442, 3091013, 3416320, 4477893, 4356853, 4969724, 3747004, 3978621, 4657338]


В таких задачах так же могут попадаться неуникальные или повторяющиеся значения, которые не хотелось бы использовать, чтобы избежать ошибок и коллизий.<br>
Вспомним упомянутый выше удобный метод **.unique()**, который возвращает нам только уникальные значения обхекта к которому мы его применям.<br>
Проверим наши вектора на уникальность.

In [ ]:
print('Уникальныых значений в массиве А: %s'% len(np.unique(customer_ids_a)))
print('Уникальныых значений в массиве Б: %s'% len(np.unique(customer_ids_b)))

Уникальныых значений в массиве А: 1000000
Уникальныых значений в массиве Б: 1000000


Все проверив, мы можем применить метод **.intersect1d()** и посмотреть на пересечение.

In [ ]:
%time
c = np.intersect1d(customer_ids_a,customer_ids_b)

CPU times: user 4 µs, sys: 0 ns, total: 4 µs
Wall time: 8.11 µs


In [ ]:
c

array([1000050, 1000063, 1000090, ..., 4999946, 4999981, 4999996])

Так как у нас довольно большое количество элементов в списке, то веротяность того что будет хотя бы одно пересечение довольно высока.
Посмотрим на то, что у нас получилось.

У нас получился вектор пересечений, который не вмещается строчку отображения в Jupyter notebook, так что давайте посмотрим на то сколько у нас получилось в нем объектов, используя метод **len()**.

In [ ]:
print('Наше пересечение равно %s объектам.' %len(c))

Наше пересечение равно 249756 объектам.


В 1 строчкe можно посчитать отношение нашего пересечения к количеству id нашего массива, в котором мы искали пересечение.

In [ ]:
len(c)/len(customer_ids_b)*100

25.0572

И предстваить его в более читаемом и осмысленном виде.

In [ ]:
print('Наше пересечение равно %s процентов.'%round(len(c)/len(customer_ids_b)*100,2))

Наше пересечение равно 25.06 процентов.


Другие методы для выполнения математических и логических операций с векторами и матрицами можно найти в документации на официальном сайте [библиотеки](https://docs.scipy.org/doc/numpy-1.15.1/reference/).

### Домашнее задание.

1) Попробуйте сами найти значения, которые не входят в наши вектора и являются противоположностью нашего пересечения.<br>

2) Сколько объектов получилось в векторе "эксклюзивных" значений?

## Массивы

Массивы – это объекты со своими атрибутами и методами.

Основным объектом NumPy является массив элементов,
как правило, чисел. Существует несколько способов создать массив. Один из
них состоит в создании массива из списка с помощью функции array().

In [ ]:
# одномерный массив
a=np.array([0.0,2.5,5.2])
a

array([0. , 2.5, 5.2])

In [ ]:
# двумерный массив
b=np.array([[1,2,3],[4,5,6]])
b

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
# преобразование одномерного массива в вектор–столбец (двумерный массив с одним столбцом)
np.linspace(-1.,1.,3)[:,None]

array([[-1.],
       [ 0.],
       [ 1.]])

Для доступа к элементам массива используются индексы. Нумерация индексов
начинается с нуля. Обе следующие записи допустимы.

In [ ]:
print(b[1,2], b[1][2])

6 6


In [ ]:
# размерность массива возвращает атрибут ndim
print(b.ndim)
# Количество элементов по каждой из координат возвращает атрибут shape
print(b.shape)
# Атрибут size возвращает количество элементов в массиве
print(b.size)
# функция len вычисляет размер массива по первой координате - количество строк
print(len(b))

2
(2, 3)
6
2


### Команды/функции создания массивов

In [ ]:
# Функция zeros() генерирует массив со всеми нулями
np.zeros(5), np.zeros([2,3])

(array([0., 0., 0., 0., 0.]),
 array([[0., 0., 0.],
        [0., 0., 0.]]))

In [ ]:
# функция ones() генерирует массив со всеми единицами
np.ones(5), np.ones([2,3])

(array([1., 1., 1., 1., 1.]),
 array([[1., 1., 1.],
        [1., 1., 1.]]))

In [ ]:
# умножение/сложение числа на массив производится поэлементно
10 * (5 + np.ones(5))

array([60., 60., 60., 60., 60.])

In [ ]:
# функция от массива выполняется поэлементно
np.sin(np.pi/6 * np.ones(5))

array([0.5, 0.5, 0.5, 0.5, 0.5])

In [ ]:
# Функция eye() генерирует единичную матрицу, размер которой передается через аргумент.
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
# генерация массива последовательно идущих чисел в модуле numpy имеются функции arange() и linspace()
print(np.arange(5,15,2.5))
# функцией linspace(a,b,N) создаётся массив N равноудаленных чисел из отрезка [a,b]
print( np.linspace(0,5,10))

[ 5.   7.5 10.  12.5]
[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]


In [ ]:
# Квадратный единичный массив можно создать функцией identity(N), где N - размер массива N x N.
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
# Функция diag(v[,k=0]) создает квадратный массив (матрицу)
print( np.diag([1,2,3]))
print( np.diag([1,2,3],1))
print( np.diag([1,2,3],-3))

[[1 0 0]
 [0 2 0]
 [0 0 3]]
[[0 1 0 0]
 [0 0 2 0]
 [0 0 0 3]
 [0 0 0 0]]
[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [1 0 0 0 0 0]
 [0 2 0 0 0 0]
 [0 0 3 0 0 0]]


In [ ]:
# массив, используя функцию над его индексами для вычисления элементов
print(np.fromfunction(lambda i: i**2,(5,)))
print(np.fromfunction(lambda i,j: i+j,(3,4)))

[ 0.  1.  4.  9. 16.]
[[0. 1. 2. 3.]
 [1. 2. 3. 4.]
 [2. 3. 4. 5.]]


Нам часто придется использовать двумерные массивы с идентичными строками
или столбцами. Для создания таких массивов используется функция
meshgrid().

Здесь генерируются две матрицы/массива. <br>Строки массива X состоят из
элементов вектора x, а количество строк определяется длиной вектора y. <br>
Наоборот, столбцы массива Y состоят из элементов вектора y, а количество
столбцов определяется длиной вектора x.

In [ ]:
x=np.array([1, 2, 3])
y=np.array([-1, 1])


X,Y=np.meshgrid(x,y)
print(X,'\n-------------\n',Y)

[[1 2 3]
 [1 2 3]] 
-------------
 [[-1 -1 -1]
 [ 1  1  1]]


# Функция meshgrid() полезна для вычисления значения функций в узлах двумерной сетки, координаты узлов которой задаются парой векторов x и y.

Для примера построим двумерный массив, элементы которого вычисляются в
узлах сетки по формуле

$z_{ij} = x_i^2 + y_j^2$
при <br>
$x_i = -2,-1,0,1,2$ <br>
и <br>
$y_j = -2,-1,0,1,2$. <br>

In [ ]:
import numpy as np

x=np.linspace(-2,2,5)
y=np.linspace(-2,2,5)

print(x,'\n-------------\n',y)
print('--'*10)
K,B=np.meshgrid(x,y)
print(K,'\n-------------\n',B)
print('--'*10)

Z=(K + B)
print(Z)

[-2. -1.  0.  1.  2.] 
-------------
 [-2. -1.  0.  1.  2.]
--------------------
[[-2. -1.  0.  1.  2.]
 [-2. -1.  0.  1.  2.]
 [-2. -1.  0.  1.  2.]
 [-2. -1.  0.  1.  2.]
 [-2. -1.  0.  1.  2.]] 
-------------
 [[-2. -2. -2. -2. -2.]
 [-1. -1. -1. -1. -1.]
 [ 0.  0.  0.  0.  0.]
 [ 1.  1.  1.  1.  1.]
 [ 2.  2.  2.  2.  2.]]
--------------------
[[-4. -3. -2. -1.  0.]
 [-3. -2. -1.  0.  1.]
 [-2. -1.  0.  1.  2.]
 [-1.  0.  1.  2.  3.]
 [ 0.  1.  2.  3.  4.]]


In [ ]:
points_X = np.array([-2, -1, 0, 1, 2, 3, 3.5, 4, 4.5, 5])
points_Y = np.array([-31, -9, 4, -1, 9, 24, 47, 92, 120, 170])

f = lambda x,k,b: 48 * (k*x + b)**2 - 128 * (k*x + b) + 83
MSE = sum([(points_Y[i] - f(points_X[i],K,B))**2 for i in range(len(points_Y))]) / len(points_Y)
MSE

array([[2.10085293e+07, 3.55633490e+06, 2.42394900e+05, 3.13134900e+05,
        1.61972930e+06],
       [1.45225933e+07, 1.90977490e+06, 5.06349000e+04, 1.26958900e+05,
        1.92528130e+06],
       [9.72225730e+06, 9.23534900e+05, 5.40290000e+03, 8.50069000e+04,
        2.88424130e+06],
       [6.28496130e+06, 3.85646900e+05, 5.32290000e+03, 1.96494900e+05,
        4.61641730e+06],
       [3.94344130e+06, 1.39438900e+05, 4.31490000e+03, 5.25934900e+05,
        7.29691330e+06]])

In [ ]:
# Имея массивы координат вершин X,Y,Z, можно построить поверхность многогранника.
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
fig=figure() # открывает/создает графическое окно
ax=Axes3D(fig) # рисует 3–мерные координатные оси
ax.plot_surface(X,Y,Z,rstride=1,cstride=1) # рисует поверхность
plt.show()

<Figure size 640x480 with 0 Axes>

In [ ]:
# В модуле numpy имеется оператор mgrid[...], близкий по смыслу
# функции meshgrid(...) (его аргументы заключаются в квадратные скобки).
x1, y1 = np.mgrid[0:8:2, -10:0:4]
print(x1,'\n-------------\n',y1)

[[0 0 0]
 [2 2 2]
 [4 4 4]
 [6 6 6]] 
-------------
 [[-10  -6  -2]
 [-10  -6  -2]
 [-10  -6  -2]
 [-10  -6  -2]]


In [ ]:
x2, y2 = np.meshgrid(np.arange(0, 8, 2), np.arange(-10, 0, 4))
print(x2)
print('--'*20)
print(y2)

# Как видите, функция meshgrid(...) создает транспонированные массивы по
# сравнению с теми, которые создает оператор mgrid[...].

[[0 2 4 6]
 [0 2 4 6]
 [0 2 4 6]]
----------------------------------------
[[-10 -10 -10 -10]
 [ -6  -6  -6  -6]
 [ -2  -2  -2  -2]]


In [ ]:
g = np.mgrid[0:8:2, -10:0:4]
g

array([[[  0,   0,   0],
        [  2,   2,   2],
        [  4,   4,   4],
        [  6,   6,   6]],

       [[-10,  -6,  -2],
        [-10,  -6,  -2],
        [-10,  -6,  -2],
        [-10,  -6,  -2]]])

Если в команде np.mgrid[start:stop:step] параметр step содержит
мнимую единицу, т.е. имеет вид Nj, то N представляет количество точек на
отрезке [start,stop] (а не шаг!), и начальная и конечная точки включаются в
массив.

In [ ]:
np.mgrid[0:6:4j, -10:-2:3j]

array([[[  0.,   0.,   0.],
        [  2.,   2.,   2.],
        [  4.,   4.,   4.],
        [  6.,   6.,   6.]],

       [[-10.,  -6.,  -2.],
        [-10.,  -6.,  -2.],
        [-10.,  -6.,  -2.],
        [-10.,  -6.,  -2.]]])

### Случайные последовательности и массивы.

Часто приходится использовать
объекты, созданные случайным образом. В Python имеется модуль random (не
путать с модулем numpy.random), который содержит функции,
предназначенные для генерирования случайных чисел, символов, и т.д., а также
последовательностей из них. Приведем краткое описание наиболее часто
используемых функций этого модуля.

In [ ]:
import random

# Функция random.seed() инициализирует генератор случайных чисел, используя системное время.
random.seed()
# Функция rnd.randrange(start,stop,step) возвращает случайно
# выбранное целое число X из диапазона start ≤ X < stop, где start,stop и
# step должны быть целыми числами.
random.randrange(5,25)

# Функция N=rnd.randint(A,B) возвращает случайное целое число N из диапазона A ≤ N ≤ B.
print(random.randint(5, 25))

# Функция rnd.choice(последовательность) возвращает случайный элемент
# из непустой последовательности, которая может быть списком, кортежем,
# массивом и т.д.
print(random.choice([1,'x',"str",(21,3),[1,2,3]]))

# Функция random.shuffle(последовательность) случайным образом
# перемешивает последовательность. Функция не работает для неизменяемых
# объектов.
z = [1,'x',"str",(21,3),[1,2,3]]
random.shuffle(z)
print(z)

# Функция X=rnd.uniform(X0,X1) возвращает случайное число с плавающей
# точкой из интервала X0 < X < X1 (или X0 ≤ X ≤ X1, зависит от настроек
# округления).
print(random.uniform(1.3, 2.4))

22
x
[[1, 2, 3], 'x', 1, (21, 3), 'str']
2.0494076122389306


## Генерация массивов в numpy

Для генерирования массивов случайных чисел предназначены функции модуля numpy.random. Они имеют сходный синтаксис с одноименными
функциями модуля random,. Приведем несколько примеров.

In [ ]:
import numpy as np

# Функция numpy.random.random(k) генерирует массив k случайных вещественных чисел из полуинтервала [0,1).
print(np.random.random(4)) # массив 4–х вещественных чисел от 0 до 1

print('----'*10)
# Имеется несколько похожих функций, отличающихся друг от друга в деталях.
print(np.random.rand(3)) # массив 3–х вещественных чисел от 0 до 1
print('----'*10)
print(np.random.rand(2,3)) # 2x3 массив вещественных чисел от 0 до 1


[0.73165944 0.71919601 0.03453924 0.21484472]
----------------------------------------
[0.28645098 0.22274396 0.45099409]
----------------------------------------
[[0.44218567 0.07877191 0.90538893]
 [0.60801849 0.95618507 0.14394724]]


In [ ]:
print( np.random.sample() ) # одно вещественное число от 0 до 1

print('----'*10)
print( np.random.sample(3) ) # массив 3–х вещественных чисел от 0 до 1

print('----'*10)
print( np.random.sample((2, 3)) ) # 2x3 массив вещественных чисел от 0 до 1

print('----'*10)
print( np.random.randint(3, 8, 5) ) # масcив 5–ти целых чисел 3≤N<8

print('----'*10)
print( np.random.randint(3, 8, (2, 4)) ) # 2x4 масcив целых чисел 3≤N<8

print('----'*10)
# Функция numpy.random.uniform(x0,x1,k) генерирует массив вещественных
# чисел, равномерно распределенных на интервале (x0,x1).
print( np.random.uniform(3, 8, (2, 4)) ) # 2x4 массив вещественных чисел

print('----'*10)
# Функция numpy.random.shuffle(массив) выполняет случайное
# перемешивание элементов массива.
z = np.arange(8)
print(z)
np.random.shuffle(z)
print(z)

print('----'*10)
# Функция numpy.random. permutation(N) возвращает массив перемешанных
# случайным образом целых чисел 0≤n<N.
print(np.random.permutation(8) )


0.2106796580492093
----------------------------------------
[0.47562482 0.29121536 0.10590992]
----------------------------------------
[[0.1595449  0.01585931 0.05136555]
 [0.61829748 0.44937375 0.67503916]]
----------------------------------------
[4 6 3 3 7]
----------------------------------------
[[6 6 6 5]
 [3 3 7 6]]
----------------------------------------
[[7.11450261 4.90704167 4.53736786 6.4961248 ]
 [6.70872974 6.57622867 3.88684619 3.52504392]]
----------------------------------------
[0 1 2 3 4 5 6 7]
[3 5 4 7 6 2 0 1]
----------------------------------------
[0 1 5 3 7 2 6 4]


In [ ]:
a = np.array([[0, 1, 2], [3, 4, 5]])
print(a)
print()

print(np.r_ ['0', a, a]) # соединение по 0–ой оси - добавили снизу

print()

print(np.r_ ['1', a, a]) # соединение по 1–ой оси - добавили справа


[[0 1 2]
 [3 4 5]]

[[0 1 2]
 [3 4 5]
 [0 1 2]
 [3 4 5]]

[[0 1 2 0 1 2]
 [3 4 5 3 4 5]]


## Матричные операции в Numpy

Все перечисленные выше функции выполняли матричные операции с
МАССИВАМИ. Если же вы хотите использовать для матричных операций
привычные обозначения, тогда вы должны преобразовать массив в матричный
тип. Для создания МАТРИЦ в NumPy предназначен специальный класс matrix,
объекты которого всегда являются двумерными. Вместо matrix можно
использовать сокращение mat. В отличие от массивов (объектов класса
ndarray), для объектов типа matrix операция /* обозначает матричное произведение, а ** – операцию матричного возведения в степень. Атрибут matrix.T возвращает транспонированную матрицу, а атрибут matrix.I – обратную матрицу. Для создания объектов matrix можно использовать специальный синтаксис, когда конструктору матрицы передается текстовая
строка. В ней элементы каждой строки матрицы разделяются пробелами, а строки – символом ; (точка с запятой).



In [ ]:
A = np.matrix('1 1;1 1'); print(A)
B = np.mat([[1,-2],[-1,1]]);print(B)

[[1 1]
 [1 1]]
[[ 1 -2]
 [-1  1]]


In [ ]:
print(A+B)
print(A*B)

[[ 2 -1]
 [ 0  2]]
[[ 0 -1]
 [ 0 -1]]


In [ ]:
print(B**2)

print(B.T)

print(B.I) # вычисление обратной матрицы


[[ 3 -4]
 [-2  3]]
[[ 1 -1]
 [-2  1]]
[[-1. -2.]
 [-1. -1.]]


- np.where - Chooses values from two arrays depending on the value of a condition array.
- np.choose - Chooses values from a list of arrays depending on the values of a given index array.
- np.select - Chooses values from a list of arrays depending on a list of conditions.
- np.nonzero - Returns an array with indices of nonzero elements.
- np.logical_and - Performs an elementwise AND operation.
- np.logical_or, np.logical_xor Elementwise OR/XOR operations.
- np.logical_not - Elementwise NOT operation (inverting).

In [4]:
import numpy as np

x = np.linspace(-4, 4, 9)
print(x)
print(np.where(x < 0, x**2, x**3))

[-4. -3. -2. -1.  0.  1.  2.  3.  4.]
[16.  9.  4.  1.  0.  1.  8. 27. 64.]


In [5]:
print(x)
print(np.select([x < -1, x < 2, x >= 2], [x**2 , x**3 , x**4]))

[-4. -3. -2. -1.  0.  1.  2.  3.  4.]
[ 16.   9.   4.  -1.   0.   1.  16.  81. 256.]


In [6]:
print(x)
print(np.choose([0, 0, 0, 1, 1, 1, 2, 2, 2], [x**2, x**3, x**4]))

[-4. -3. -2. -1.  0.  1.  2.  3.  4.]
[ 16.   9.   4.  -1.   0.   1.  16.  81. 256.]


In [7]:
print(x)
print(np.nonzero(abs(x) > 2))

print(x[np.nonzero(abs(x) > 2)])

print(x[abs(x) > 2])


[-4. -3. -2. -1.  0.  1.  2.  3.  4.]
(array([0, 1, 7, 8]),)
[-4. -3.  3.  4.]
[-4. -3.  3.  4.]
